// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxpH9Jm4gkbAxpl8LVYbMC7hJ1NBGDbW8',
    appId: '1:571563589094:web:15499f36236d7618faea27',
    messagingSenderId: '571563589094',
    projectId: 'event-flow-7b127',
    authDomain: 'event-flow-7b127.firebaseapp.com',
    storageBucket: 'event-flow-7b127.appspot.com',
    measurementId: 'G-20K28RYKG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJpYXGv07ptc0SANWbZt8ePXgAP6viITU',
    appId: '1:571563589094:android:4e462cf70b86a2a0faea27',
    messagingSenderId: '571563589094',
    projectId: 'event-flow-7b127',
    storageBucket: 'event-flow-7b127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKZcOwT0xvqgbCnOyHLHmgtDriTfbt_A',
    appId: '1:571563589094:ios:bcc8129376cfbb93faea27',
    messagingSenderId: '571563589094',
    projectId: 'event-flow-7b127',
    storageBucket: 'event-flow-7b127.appspot.com',
    iosBundleId: 'com.example.eventFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKZcOwT0xvqgbCnOyHLHmgtDriTfbt_A',
    appId: '1:571563589094:ios:bcc8129376cfbb93faea27',
    messagingSenderId: '571563589094',
    projectId: 'event-flow-7b127',
    storageBucket: 'event-flow-7b127.appspot.com',
    iosBundleId: 'com.example.eventFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxpH9Jm4gkbAxpl8LVYbMC7hJ1NBGDbW8',
    appId: '1:571563589094:web:376fdf40b8f28c29faea27',
    messagingSenderId: '571563589094',
    projectId: 'event-flow-7b127',
    authDomain: 'event-flow-7b127.firebaseapp.com',
    storageBucket: 'event-flow-7b127.appspot.com',
    measurementId: 'G-7NT8ZWVXQH',
  );
}
